/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Friend_tech } from "./Friend_tech";
export type { Multicall } from "./Multicall";
export * as factories from "./factories";
export { Friend_tech__factory } from "./factories/Friend_tech__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
