/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Friend_tech__factory } from "./Friend_tech__factory";
export { Multicall__factory } from "./Multicall__factory";
